version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: omnicorp_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: omnicorp
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: omnicorp_user
      MYSQL_PASSWORD: omnicorp_password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --bind-address=0.0.0.0
      --innodb-buffer-pool-size=128M
      --skip-name-resolve
    networks:
      omnicorp-network:
        aliases:
          - db
          - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: omnicorp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - omnicorp-network

  backend:
    image: python:3.9-slim
    container_name: omnicorp_backend
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - omnicorp-network
    environment:
      - DATABASE_URL=mysql+pymysql://omnicorp_user:omnicorp_password@db:3306/omnicorp
      - USE_MOCK_LDAP=false
      - AD_SERVER=10.98.132.248
      - AD_DOMAIN=SSODC.Local
      - AD_BASE_DN=OU=Usuarios,DC=SSODC,DC=Local
      - AD_USERNAME=ldap_service_account
      - AD_PASSWORD=ldap_service_password
      - DEBUG=true
    command: >
      bash -c "apt-get update && 
      apt-get install -y build-essential libldap2-dev libsasl2-dev ldap-utils && 
      pip install -r requirements.txt && 
      sleep 30 &&
      python run.py"

  frontend:
    image: node:16-alpine
    container_name: omnicorp_frontend
    restart: always
    working_dir: /app
    volumes:
      - ./app/frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - omnicorp-network
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - WDS_SOCKET_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: >
      sh -c "mkdir -p /app/node_modules/.cache &&
      chmod 777 /app/node_modules/.cache &&
      npm install &&
      npm start"

  redis:
    image: redis:alpine
    container_name: omnicorp_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - omnicorp-network

volumes:
  frontend_node_modules:
  mysql_data:

networks:
  omnicorp-network:
    driver: bridge 